apiVersion: v1
kind: Service
metadata:
  name: categories-slave-svc
  labels:
    jmeter_mode: categories-slave
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: categories-slave
