apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: categories-master
  labels:
    jmeter_mode: categories-master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: categories-master
  template:
    metadata:
      labels:
        jmeter_mode: categories-master 
    spec:
      containers:
      - name: categories-master
        image: relvan/jmeter-master
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
            subPath: "load_test"
        ports:
        - containerPort: 60000
      volumes:
      - name: loadtest 
        configMap:
         name: jmeter-load-test
      nodeSelector:
        type: master2
